openapi: 3.0.0
paths:
  "/api/file/upload/{fileName}":
    get:
      operationId: FileController_generateUploadUrl
      parameters:
        - name: fileName
          required: true
          in: path
          description: File Name
          schema: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileResponseDto"
      tags:
        &a1
        - File Module
  "/api/file/download/{fileName}":
    get:
      operationId: FileController_generateDownloadUrl
      parameters:
        - name: fileName
          required: true
          in: path
          description: File Name
          schema: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileResponseDto"
      tags: *a1
  /api/file:
    post:
      operationId: FileController_test
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileResponseDto"
      tags: *a1
info:
  title: Swagger API
  description: Swagger APIs for application
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    FileResponseDto:
      type: object
      properties:
        fileName:
          default: image.png
          type: string
        presignedUrl:
          default: www.google.com
          type: string
      required: []
