openapi: 3.0.0
paths:
  "/api/file/{fileName}":
    get:
      operationId: FileController_generateUploadUrl
      parameters:
        - name: fileName
          required: true
          in: path
          description: File Name
          schema: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileUploadResponseDto"
      tags:
        - File Module
info:
  title: Swagger API
  description: Swagger APIs for application
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    FileUploadResponseDto:
      type: object
      properties: {}
