openapi: 3.0.0
paths:
  "/api/file/upload/{fileName}":
    get:
      operationId: FileController_generateUploadUrl
      parameters:
        - name: fileName
          required: true
          in: path
          description: File Name
          schema: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FilePresignedResponseDto"
      tags:
        &a1
        - File Module
  "/api/file/download/{fileName}":
    get:
      operationId: FileController_generateDownloadUrl
      parameters:
        - name: fileName
          required: true
          in: path
          description: File Name
          schema: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FilePresignedResponseDto"
      tags: *a1
  "/api/file/{id}":
    get:
      operationId: FileController_getFileInfo
      parameters:
        - name: id
          required: true
          in: path
          description: File ID
          schema: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileResponseDto"
      tags: *a1
    put:
      operationId: FileController_updateMainImage
      parameters:
        - name: mainImage
          required: true
          in: query
          description: Main image to be used for Ximilar API
          schema: {}
        - name: id
          required: true
          in: path
          description: File ID
          schema: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdatedFileResponseDto"
      tags: *a1
info:
  title: Swagger API
  description: Swagger APIs for application
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    FilePresignedResponseDto:
      type: object
      properties:
        fileName:
          default: image.png
          type: string
        presignedUrl:
          default: www.google.com
          type: string
      required: []
    FileResponseDto:
      type: object
      properties:
        sku_id:
          default: SK 0001
          type: string
        main_file:
          default: image.png
          type: string
        updated_time:
          default: updated_time
          type: string
      required: []
    UpdatedFileResponseDto:
      type: object
      properties:
        sku_id:
          default: SK 0001
          type: string
        main_file:
          default: image.png
          type: string
        updated_time:
          default: updated_time
          type: string
      required: []
