service: nestjs-serverless

frameworkVersion: '3'

plugins:
    - serverless-jetpack

provider:
    name: aws
    runtime: nodejs14.x
    region: ap-southeast-1 # or whatever your region is

functions:
    api:
        handler: dist/lambda.handler
        events:
            - http:
                  method: any
                  path: /{proxy+}
