Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.SKU_DYNAMODB_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: sku_id
          KeyType: HASH
        - AttributeName: updated_time
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: sku_id
          AttributeType: S
        - AttributeName: updated_time
          AttributeType: S
