Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.SKU_DYNAMODB_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: sku_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: sku_id
          AttributeType: S
        - AttributeName: updated_time
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.SKU_TIMESTAMP_INDEX_TABLE}
          KeySchema:
            - AttributeName: updated_time
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  EcwidTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.ECWID_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id 
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id 
          AttributeType: S
        - AttributeName: updated_time
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.ECWID_TIMESTAMP_INDEX_TABLE}
          KeySchema:
            - AttributeName: updated_time
              KeyType: HASH
          Projection:
            ProjectionType: ALL
