Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.SKU_DYNAMODB_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: sku_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: sku_id
          AttributeType: S
        - AttributeName: updated_time
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.SKU_TIMESTAMP_INDEX_TABLE}
          KeySchema:
            - AttributeName: updated_time
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  EcwidTranslationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.TRANSLATION_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: ID 
          AttributeType: S

  IndexingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.INDEXING_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id 
          AttributeType: N

  BrandTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.BRAND_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id 
          AttributeType: N

  SubcategoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.SUBCATEGORY_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id 
          AttributeType: N
    
  RatingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.RATING_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id 
          AttributeType: N
        
  XimilarTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.XIMILAR_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id 
          AttributeType: S

  EcwidTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.ECWID_TABLE}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id 
          AttributeType: S
